/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 11 17:55:11 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package mx.ipn.web.dao;

/*
 * For Table Alumno
 */
public class Alumno implements java.io.Serializable, Cloneable {
   

    /**
	 * 
	 */
	private static final long serialVersionUID = 6384190648895404190L;

	/* idAlumno, PK */
    protected int idalumno;

    /* boleta */
    protected String boleta;

    /* nombre */
    protected String nombre;

    /* apellidoMaterno */
    protected String apellidomaterno;

    /* apellidoPaterno */
    protected String apellidopaterno;

    /* email */
    protected String email;

    /* foto */
    protected java.sql.Blob foto;

    /* idCarrera */
    protected Carrera carrera;

    /* Return the key object. */
    

    /* idAlumno, PK */
    public int getIdalumno() {
        return idalumno;
    }

    /* idAlumno, PK */
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }

    /* boleta */
    public String getBoleta() {
        return boleta;
    }

    /* boleta */
    public void setBoleta(String boleta) {
        this.boleta = boleta;
    }

    /* nombre */
    public String getNombre() {
        return nombre;
    }

    /* nombre */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /* apellidoMaterno */
    public String getApellidomaterno() {
        return apellidomaterno;
    }

    /* apellidoMaterno */
    public void setApellidomaterno(String apellidomaterno) {
        this.apellidomaterno = apellidomaterno;
    }

    /* apellidoPaterno */
    public String getApellidopaterno() {
        return apellidopaterno;
    }

    /* apellidoPaterno */
    public void setApellidopaterno(String apellidopaterno) {
        this.apellidopaterno = apellidopaterno;
    }

    /* email */
    public String getEmail() {
        return email;
    }

    /* email */
    public void setEmail(String email) {
        this.email = email;
    }

    /* foto */
    public java.sql.Blob getFoto() {
        return foto;
    }

    /* foto */
    public void setFoto(java.sql.Blob foto) {
        this.foto = foto;
    }

    /* idCarrera */
    public Carrera getCarrera() {
        return carrera;
    }

    /* idCarrera */
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    
    public String getNombreCompleto( ){
    	return nombre + " " + apellidopaterno + " " + apellidomaterno;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Alumno))
            return false;

        Alumno bean = (Alumno) obj;

        if (this.idalumno != bean.idalumno)
            return false;

        if (this.boleta == null) {
            if (bean.boleta != null)
                return false;
        }
        else if (!this.boleta.equals(bean.boleta)) 
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.apellidomaterno == null) {
            if (bean.apellidomaterno != null)
                return false;
        }
        else if (!this.apellidomaterno.equals(bean.apellidomaterno)) 
            return false;

        if (this.apellidopaterno == null) {
            if (bean.apellidopaterno != null)
                return false;
        }
        else if (!this.apellidopaterno.equals(bean.apellidopaterno)) 
            return false;

        if (this.email == null) {
            if (bean.email != null)
                return false;
        }
        else if (!this.email.equals(bean.email)) 
            return false;

        if (this.foto == null) {
            if (bean.foto != null)
                return false;
        }
        else if (!this.foto.equals(bean.foto)) 
            return false;
        if( !this.carrera.equals( bean.getCarrera() ) ){
        	return false;
        }

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Alumno bean = new Alumno();
        bean.idalumno = this.idalumno;
        bean.boleta = this.boleta;
        bean.nombre = this.nombre;
        bean.apellidomaterno = this.apellidomaterno;
        bean.apellidopaterno = this.apellidopaterno;
        bean.email = this.email;
        bean.foto = this.foto;   // The field (java.sql.Blob) is not cloned actually.
        bean.carrera = this.carrera;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idalumno").append(" = ").append(idalumno).append("]").append(sep);
        sb.append("[").append("boleta").append(" = ").append(boleta).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("apellidomaterno").append(" = ").append(apellidomaterno).append("]").append(sep);
        sb.append("[").append("apellidopaterno").append(" = ").append(apellidopaterno).append("]").append(sep);
        sb.append("[").append("email").append(" = ").append(email).append("]").append(sep);
        sb.append("[").append("foto").append(" = ").append(foto).append("]").append(sep);
        sb.append("[").append("idcarrera").append(" = ").append( carrera.toString( ) ).append("]").append(sep);
        return sb.toString();
    }
}