/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 11 17:55:11 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package mx.ipn.web.dao;

/*
 * For Table Calificacion
 */
public class Calificacion implements java.io.Serializable, Cloneable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -1429898722883577852L;

	/* idCalificacion, PK */
    protected int idcalificacion;

    /* calificacion */
    protected String calificacion;

    /* idAlumno */
    protected int idalumno;

    
    
    public void setIdcalificacion(int idcalificacion) {
		this.idcalificacion = idcalificacion;
	}

	/* idCalificacion, PK */
    public int getIdcalificacion() {
        return idcalificacion;
    }

    /* calificacion */
    public String getCalificacion() {
        return calificacion;
    }

    /* calificacion */
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }

    /* idAlumno */
    public int getIdalumno() {
        return idalumno;
    }

    /* idAlumno */
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Calificacion))
            return false;

        Calificacion bean = (Calificacion) obj;

        if (this.idcalificacion != bean.idcalificacion)
            return false;

        if (this.calificacion == null) {
            if (bean.calificacion != null)
                return false;
        }
        else if (!this.calificacion.equals(bean.calificacion)) 
            return false;

        if (this.idalumno != bean.idalumno)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Calificacion bean = new Calificacion();
        bean.idcalificacion = this.idcalificacion;
        bean.calificacion = this.calificacion;
        bean.idalumno = this.idalumno;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcalificacion").append(" = ").append(idcalificacion).append("]").append(sep);
        sb.append("[").append("calificacion").append(" = ").append(calificacion).append("]").append(sep);
        sb.append("[").append("idalumno").append(" = ").append(idalumno).append("]").append(sep);
        return sb.toString();
    }
}