/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 11 17:55:11 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package mx.ipn.web.dao;

/*
 * For Table Carrera
 */
public class Carrera implements java.io.Serializable, Cloneable {
	
  

    /**
	 * 
	 */
	private static final long serialVersionUID = -5721095440783240255L;

	/* idCarrera, PK */
    protected int idcarrera;

    /* nombre */
    protected String nombre;

    /* duracion */
    protected String duracion;

    /* idEscuela */
    //eliminar o comentar "idEscuela"
    protected int idescuela;//<----relacion estilo bd
    //private Escuela escuela;//<-----relacion estilo JavaBean

    /* Return the key object. */
   

    /* idCarrera, PK */
    public int getIdcarrera() {
        return idcarrera;
    }

    /* idCarrera, PK */
    public void setIdcarrera(int idcarrera) {
        this.idcarrera = idcarrera;
      
    }

    /* nombre */
    public String getNombre() {
        return nombre;
    }

    /* nombre */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /* duracion */
    public String getDuracion() {
        return duracion;
    }

    /* duracion */
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }

    /* idEscuela */
    public int getIdescuela() {
        return idescuela;
    }

    /* idEscuela */
    public void setIdescuela(int idescuela) {
        this.idescuela = idescuela;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Carrera))
            return false;

        Carrera bean = (Carrera) obj;

        if (this.idcarrera != bean.idcarrera)
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.duracion == null) {
            if (bean.duracion != null)
                return false;
        }
        else if (!this.duracion.equals(bean.duracion)) 
            return false;

        if (this.idescuela != bean.idescuela)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Carrera bean = new Carrera();
        bean.idcarrera = this.idcarrera;
        bean.nombre = this.nombre;
        bean.duracion = this.duracion;
        bean.idescuela = this.idescuela;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcarrera").append(" = ").append(idcarrera).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("duracion").append(" = ").append(duracion).append("]").append(sep);
        sb.append("[").append("idescuela").append(" = ").append(idescuela).append("]").append(sep);
        return sb.toString();
    }
}