/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 11 17:55:12 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package mx.ipn.web.dao;

/*
 * For Table Materia
 */
public class Materia implements java.io.Serializable, Cloneable {
   

    /**
	 * 
	 */
	private static final long serialVersionUID = 5820689918216596084L;

	/* idMateria, PK */
    protected int idmateria;

    /* nombre */
    protected String nombre;

    /* idAlumno */
    protected int idalumno;

    /* Return the key object. */
    

    /* idMateria, PK */
    public int getIdmateria() {
        return idmateria;
    }

    /* idMateria, PK */
    public void setIdmateria(int idmateria) {
        this.idmateria = idmateria;
        
    }

    /* nombre */
    public String getNombre() {
        return nombre;
    }

    /* nombre */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /* idAlumno */
    public int getIdalumno() {
        return idalumno;
    }

    /* idAlumno */
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Materia))
            return false;

        Materia bean = (Materia) obj;

        if (this.idmateria != bean.idmateria)
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.idalumno != bean.idalumno)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Materia bean = new Materia();
        bean.idmateria = this.idmateria;
        bean.nombre = this.nombre;
        bean.idalumno = this.idalumno;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idmateria").append(" = ").append(idmateria).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("idalumno").append(" = ").append(idalumno).append("]").append(sep);
        return sb.toString();
    }
}