/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 11 17:55:12 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package mx.ipn.web.dao;

/*
 * For Table Respuesta
 */
public class Respuesta implements java.io.Serializable, Cloneable {
   

    /**
	 * 
	 */
	private static final long serialVersionUID = -8856540927374594320L;

	/* idRespuesta, PK */
    protected int idrespuesta;

    /* resultado */
    protected String resultado;

    /* idPregunta */
    protected int idpregunta;

    /* correcto */
    protected byte correcto;

    /* Return the key object. */
    

    /* idRespuesta, PK */
    public int getIdrespuesta() {
        return idrespuesta;
    }

    /* idRespuesta, PK */
    public void setIdrespuesta(int idrespuesta) {
        this.idrespuesta = idrespuesta;
        
    }

    /* resultado */
    public String getResultado() {
        return resultado;
    }

    /* resultado */
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }

    /* idPregunta */
    public int getIdpregunta() {
        return idpregunta;
    }

    /* idPregunta */
    public void setIdpregunta(int idpregunta) {
        this.idpregunta = idpregunta;
    }

    /* correcto */
    public byte getCorrecto() {
        return correcto;
    }

    /* correcto */
    public void setCorrecto(byte correcto) {
        this.correcto = correcto;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Respuesta))
            return false;

        Respuesta bean = (Respuesta) obj;

        if (this.idrespuesta != bean.idrespuesta)
            return false;

        if (this.resultado == null) {
            if (bean.resultado != null)
                return false;
        }
        else if (!this.resultado.equals(bean.resultado)) 
            return false;

        if (this.idpregunta != bean.idpregunta)
            return false;

        if (this.correcto != bean.correcto)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Respuesta bean = new Respuesta();
        bean.idrespuesta = this.idrespuesta;
        bean.resultado = this.resultado;
        bean.idpregunta = this.idpregunta;
        bean.correcto = this.correcto;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idrespuesta").append(" = ").append(idrespuesta).append("]").append(sep);
        sb.append("[").append("resultado").append(" = ").append(resultado).append("]").append(sep);
        sb.append("[").append("idpregunta").append(" = ").append(idpregunta).append("]").append(sep);
        sb.append("[").append("correcto").append(" = ").append(correcto).append("]").append(sep);
        return sb.toString();
    }
}