/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 11 17:55:11 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package mx.ipn.web.dao.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import mx.ipn.web.dao.Calificacion;
import mx.ipn.web.dao.dao.CalificacionDAO;

/**
 * This class provides methods to populate DB Table of Calificacion
 */
public class CalificacionDAOImpl implements CalificacionDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Calificacion ("
        + "idCalificacion, calificacion, idAlumno"
        + ") VALUES (?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idCalificacion, calificacion, idAlumno "
        + "FROM Calificacion WHERE "
        + "idCalificacion = ?";
    
    private static final String SQL_SELECT_ALL =
            "SELECT "
            + "idCalificacion, calificacion, idAlumno "
            + "FROM Calificacion";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Calificacion SET "
        + "calificacion = ?, idAlumno = ? "
        + "WHERE "
        + "idCalificacion = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Calificacion WHERE "
        + "idCalificacion = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Calificacion bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdcalificacion());
            ps.setString(2, bean.getCalificacion());
            ps.setInt(3, bean.getIdalumno());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Calificacion load(int key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key );
            rs = ps.executeQuery();
            List<Calificacion> results = getResults(rs);
            if (results.size() > 0)
                return (Calificacion) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }
    
    public List<Calificacion> loadAll( Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT_ALL);
            rs = ps.executeQuery();
            List<Calificacion> results = getResults(rs);
            return results;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Calificacion bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getCalificacion());
            ps.setInt(2, bean.getIdalumno());
            ps.setInt(3, bean.getIdcalificacion());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(int key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key);
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Calificacion> getResults(ResultSet rs) throws SQLException {
        List<Calificacion> results = new ArrayList<Calificacion>();
        while (rs.next()) {
            Calificacion bean = new Calificacion();
            bean.setIdcalificacion(rs.getInt("idCalificacion"));
            bean.setCalificacion(rs.getString("calificacion"));
            bean.setIdalumno(rs.getInt("idAlumno"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}