/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 11 17:55:11 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package mx.ipn.web.dao.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;


import mx.ipn.web.dao.Carrera;
import mx.ipn.web.dao.dao.CarreraDAO;

/**
 * This class provides methods to populate DB Table of Carrera
 */
public class CarreraDAOImpl implements CarreraDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Carrera ("
        + "idCarrera, nombre, duracion, idEscuela"
        + ") VALUES (?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idCarrera, nombre, duracion, idEscuela "
        + "FROM Carrera WHERE "
        + "idCarrera = ?";

    /*Metodo para seleccionar todo*/
    private static final String SQL_SELECT_ALL=
    		"SELECT " 
    		+ "idCarrera, nombre, duracion, idEscuela "
    		+ "FROM Carrera" ;

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Carrera SET "
        + "nombre = ?, duracion = ?, idEscuela = ? "
        + "WHERE "
        + "idCarrera = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Carrera WHERE "
        + "idCarrera = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Carrera bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdcarrera());
            ps.setString(2, bean.getNombre());
            ps.setString(3, bean.getDuracion());
            ps.setInt(4, bean.getIdescuela());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Carrera load(int key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key );
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Carrera) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }
    //Para la consulta de todo
    
    public List<Carrera> loadAll( Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT_ALL);
            rs = ps.executeQuery();
            List<Carrera> results = getResults(rs);
            return results;
        }finally {
            close(rs);
            close(ps);
        }
    }
    
    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Carrera bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getNombre());
            ps.setString(2, bean.getDuracion());
            ps.setInt(3, bean.getIdescuela());
            ps.setInt(4, bean.getIdcarrera());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(int key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key );
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Carrera> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Carrera>();
        while (rs.next()) {
            Carrera bean = new Carrera();
            bean.setIdcarrera(rs.getInt("idCarrera"));
            bean.setNombre(rs.getString("nombre"));
            bean.setDuracion(rs.getString("duracion"));
            bean.setIdescuela(rs.getInt("idEscuela"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }


}
