/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 11 17:55:12 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package mx.ipn.web.dao.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import mx.ipn.web.dao.*;
import mx.ipn.web.dao.dao.PreguntaDAO;

/**
 * This class provides methods to populate DB Table of Pregunta
 */
public class PreguntaDAOImpl implements PreguntaDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Pregunta ("
        + "idPregunta, pregunta, idExamen"
        + ") VALUES (?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idPregunta, pregunta, idExamen "
        + "FROM Pregunta WHERE "
        + "idPregunta = ?";

    /*Selecionar todo*/
    private static final String SQL_SELECT_ALL =
    	"SELECT " 
    	+"idPregunta,pregunta,idExamen "
    	+"FROM Pregunta";
     /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Pregunta SET "
        + "pregunta = ?, idExamen = ? "
        + "WHERE "
        + "idPregunta = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Pregunta WHERE "
        + "idPregunta = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Pregunta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdpregunta());
            ps.setString(2, bean.getPregunta());
            ps.setInt(3, bean.getIdexamen());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Pregunta load(int key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key);
            rs = ps.executeQuery();
            List<Pregunta> results = getResults(rs);
            if (results.size() > 0)
                return (Pregunta) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /*Metodo loadAll*/
    
    @Override
    /**
      *Lee los parametros del query
      * Trae todo lo de la lista
      */
    public List<Pregunta> loadAll(Connection conn) throws SQLException {
    	PreparedStatement ps = null;
    	ResultSet rs = null;
    	List<Pregunta> list = null;
    	try{
    		ps = conn.prepareStatement( SQL_SELECT_ALL );
    		rs = ps.executeQuery();
    		list = this.getResults( rs );
    		return list;
    	}catch( Exception ex ){
    		ex.printStackTrace( );
    	}finally {
    		close(rs);
    		close(ps);
    	}
    	//el control llega aqui...
    	return null;

    }
    
    
    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Pregunta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getPregunta());
            ps.setInt(2, bean.getIdexamen());
            ps.setInt(3, bean.getIdpregunta());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(int key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key);
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Pregunta> getResults(ResultSet rs) throws SQLException {
        List<Pregunta> results = new ArrayList<Pregunta>();
        while (rs.next()) {
            Pregunta bean = new Pregunta();
            bean.setIdpregunta(rs.getInt("idPregunta"));
            bean.setPregunta(rs.getString("pregunta"));
            bean.setIdexamen(rs.getInt("idExamen"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }

	
}