/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 11 17:55:12 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package mx.ipn.web.dao.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import mx.ipn.web.dao.*;
import mx.ipn.web.dao.dao.RespuestaDAO;

/**
 * This class provides methods to populate DB Table of Respuesta
 */
public class RespuestaDAOImpl implements RespuestaDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Respuesta ("
        + "idRespuesta, resultado, idPregunta, correcto"
        + ") VALUES (?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idRespuesta, resultado, idPregunta, correcto "
        + "FROM Respuesta WHERE "
        + "idRespuesta = ?";
    private static final String SQL_SELECT_ALL=
    	"SELECT "
    	+" idRespuesta,resultado,idPregunta,correcto "
    	+"FROM Respuesta";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Respuesta SET "
        + "resultado = ?, idPregunta = ?, correcto = ? "
        + "WHERE "
        + "idRespuesta = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Respuesta WHERE "
        + "idRespuesta = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Respuesta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdrespuesta());
            ps.setString(2, bean.getResultado());
            ps.setInt(3, bean.getIdpregunta());
            ps.setByte(4, bean.getCorrecto());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Respuesta load(int key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key);
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Respuesta) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }
    /*Metodo de loadAll*/
    public List<Respuesta> loadAll(Connection conn)throws SQLException{
    	PreparedStatement ps = null;
    	ResultSet rs = null;
    	try {
    		ps = conn.prepareStatement(SQL_SELECT_ALL);
    		rs = ps.executeQuery();
    		List<Respuesta> results = getResults(rs);
    		return results;
    	}finally{
    		close(ps);
    		close (rs);
    	}
    	
    	
    }
   
    

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Respuesta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getResultado());
            ps.setInt(2, bean.getIdpregunta());
            ps.setByte(3, bean.getCorrecto());
            ps.setInt(4, bean.getIdrespuesta());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(int key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key);
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Respuesta> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Respuesta>();
        while (rs.next()) {
            Respuesta bean = new Respuesta();
            bean.setIdrespuesta(rs.getInt("idRespuesta"));
            bean.setResultado(rs.getString("resultado"));
            bean.setIdpregunta(rs.getInt("idPregunta"));
            bean.setCorrecto(rs.getByte("correcto"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }

	
}